### ISSUE TITLE
Join on parent field

### ISSUE THREAD

**Issue by thetuningspoon** [baumrock/RockFinder3#3]
It doesn't seem to be possible to join a rockfinder on the parent_id column.

**Comment by thetuningspoon** [comment]
I fixed this by adding an if condition in getJoinSQL()

```
    // return the sql query to join the subquery as new table alias
    if($col instanceof BaseColumn) {
      return "(\n  $subquery\n) AS `{$slave->name}` ON `{$slave->name}`.`id` = `pages`.`{$col->name}`";
    }
    else {
      return "(\n  $subquery\n) AS `{$slave->name}` ON `{$slave->name}`.`id` = `{$col->tableAlias}`.`data`";
    }
```

**Comment by BernhardBaumrock** [comment]
Hi @thetuningspoon ,
thx for the code snippet. Could you please provide more details and an example what you are doing and why this is/was a problem? Thx :)

**Comment by thetuningspoon** [comment]
Hi @BernhardBaumrock. I needed to include some fields from the parent pages in each row. In this case I was getting order items and needed information about the order too, which is the parent of the order item.
