### ISSUE TITLE
Support for Combo-Field

### ISSUE THREAD

**Issue by flipzoom** [baumrock/RockFinder3#4]
Hi Bernhard, 

have you ever tried to run RF3 with the Profield "Combo"? I can only select the combo field, but then consequently only get the entire JSON from the "data" column. But can't access the subfields directly via the selector. For example: 

```php
$invoices = $rockfinder
                ->find("template=invoice, customer={$page->id}")
                ->addColumns(['invoice.gross', 'invoice.vat']);
print_r($invoices->getRows());
```

**Comment by BernhardBaumrock** [comment]
Hi David,
adding columns via subfield selectors has never been thought of from my side ;) I'd wonder if that worked anywhere else. I've also never worked with combo field yet. I'll close the issue.
I could have a look if combo field could be supported though. If you need help please write me a PM in the forum (or email).
Thx
